StartupEvents.registry("block", (event) => {
    event.create("dust")
    .sandSoundType()
    .hardness(0.5)
    .resistance(0.5)
    .tagBoth("kubejs:dust")
    .tagBoth("c:dust")
    .requiresTool(true)
    .tagBlock("minecraft:mineable/pickaxe")
    .tagBlock("minecraft:mineable/shovel")
})